





search<-"Q&A The launch of the new EV system (NON-COMPLIANCE Q-4.28): EEE CASE ORIGINATED FROM NCA SENT BACK TO EUDRAVIGILANCE"


load("INFORMACION_ADICIONAL_NOTIFICACION.RData")

load("INFADIC_COMENTARIOS_NOTIFICADOR.RData")

load("INFADIC_DIAGNOSTICO_EMISOR.RData")
